a1=input('Input Your 1 Number:')
a2=input('Input Your 2 Number:')
a3=input('Your Your  3 Number :')
a4=input('Your Your  4 Number:')
a5=input('Your Your  5 Number:')
print("Float of %s Equal "%a1,float(a1))
print("complex of %s Equal "%a1,complex(a1))
print("Float of %s Equal "%a2,float(a2))
print("complex of %s Equal "%a2,complex(a2))
print("Float of %s Equal "%a3,float(a3))
print("complex of %s Equal "%a3,complex(a3)) 
print("Float of %s Equal "%a4,float(a4))
print("complex of %s Equal "%a4,complex(a4))
print("Float of %s Equal "%a5,float(a5))
print("complex of %s Equal "%a5,complex(a5))
